
// Print the letters a through z.
/*
c : char = "a";

while c <= "z" {
	print c;
	c = c + 1;
}

INTEGER : const int = 23;

j : int = INTEGER;
k : int = 2;

a : int = k = j;

print k;

*/

add() : func {
print "a";
}

add();

a : int = 1;
b : int = 2;
c : int = 3;

c = a = b;

print a;
print b;
print c;

// Shows the end of the code

/*
	add(int : a, int : b) : fun -> int {
		return a + b;
	}
*/

`