apples := 2;

if apples == 5 {
    apples = 2;
    if apples == 2 {
        apples = 4;
    } elif apples == 4 {
        apples = 2;
    }
} elif apples == 2 {
    apples = 1;
} else {
    apples = 8;
}

loop_var := 0;

while loop_var < 5 {    //This is a loop!
    loop_var = loop_var + 2;
}

_legal_var2 : int;

_legal_var2 = 99;

new_var := 2;

new_var = new_var + _legal_var2;

void func() { }

/*
    This is not a mistake. The ` is needed to tell the lexer when to stop reading because  
    it is reading only a byte at a time and can't actually read in an EOF (which has a value
    of -1).
*/
`