#ifndef OP_CODES_H
#define OP_CODES_H

enum {
    OPCODE_ADD, 
    OPCODE_MOV, 
    OPCODE_SUB, 
    OPCODE_PUSH, 
    OPCODE_POP, 
    OPCODE_SYS_CALL, 
    OPCODE_CMP,
    OPCODE_LD,
    OPCODE_JMP,
    OPCODE_MULTIPLY,
    OPCODE_DIVIDE,
    OPCODE_MODULO
};

#endif //!OP_CODES_H